{"name": "test_add_evidence", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'LocatorsCaseDetails' has no attribute 'evidence_tab_id'", "trace": "self = <test_case_details.TestCaseDetails object at 0x0E7CCA30>\n\n    def test_add_evidence(self):\n        driver = self.driver\n        self.login()\n>       case_details = CaseDetails(driver)\n\ntest_case_details.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.CaseDetailsPage.CaseDetails object at 0x0E7CCE10>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f4ef06ff1384b81c1153f05830192605\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self.table_last_row_xpath = LocatorsCaseDetails.table_last_row_xpath\n        self.expense_tab_id = Locators.expense_tab_id\n        self.tab_h4_title_class = LocatorsCaseDetails.tab_h4_title_class\n    \n        self.received_payment_txtbox_id = LocatorsCaseDetails.received_payment_txtbox_id\n        self.received_payment_currency_dropbox_id = LocatorsCaseDetails.received_payment_currency_dropbox_id\n        self.received_payment_detail_txtbox_id = LocatorsCaseDetails.received_payment_detail_txtbox_id\n        self.received_payment_date_datetime_id = LocatorsCaseDetails.received_payment_date_datetime_id\n        self.received_payment_add_btn_xpath = LocatorsCaseDetails.received_payment_add_btn_xpath\n    \n        self.expense_and_payment_div_id = LocatorsCaseDetails.expense_and_payment_div_id\n    \n        self.expense_txtbox_id = LocatorsCaseDetails.expense_txtbox_id\n        self.expense_dropbox_id = LocatorsCaseDetails.expense_dropbox_id\n        self.expense_detail_txtbox_id = LocatorsCaseDetails.expense_detail_txtbox_id\n        self.expense_date_datetime_id = LocatorsCaseDetails.expense_date_datetime_id\n        self.expense_add_btn_xpath = LocatorsCaseDetails.expense_add_btn_xpath\n    \n        self.add_new_evidence_btn_id = LocatorsCaseDetails.add_new_evidence_btn_id\n>       self.evidence_tab_id = LocatorsCaseDetails.evidence_tab_id\nE       AttributeError: type object 'LocatorsCaseDetails' has no attribute 'evidence_tab_id'\n\n..\\Pages\\CaseDetailsPage.py:42: AttributeError"}, "attachments": [{"name": "stdout", "source": "61257d1f-e768-4ad4-9ae7-36b9eba22eea-attachment.txt", "type": "text/plain"}], "start": 1568205853536, "stop": 1568205864109, "uuid": "9b1d7341-a743-4776-888c-1c4e5c8cfd98", "historyId": "1b0719228033f564f68e8171fe6bf095", "testCaseId": "b97ef1dc24e3a37bb3c5fd0020ba1941", "fullName": "test_case_details.TestCaseDetails#test_add_evidence", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_case_details"}, {"name": "subSuite", "value": "TestCaseDetails"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "12688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_details"}]}