{"uuid": "00684d44-78c4-4da3-82a7-59bf62005744", "children": ["f3792ab5-0910-4189-ba29-123ce02d8153"], "befores": [{"name": "set_up", "status": "passed", "start": 1568412876119, "stop": 1568412880161}], "afters": [{"name": "set_up::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=77.0.3865.75)\n  (Driver info: chromedriver=71.0.3578.137 (86ee722808adfe9e3c92e6e8ea746ade08423c7e),platform=Windows NT 10.0.15063 x86_64)\n\n", "trace": "  File \"c:\\users\\z003d7tu\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\z003d7tu\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\_python\\themis\\Tests/..\\Base\\base.py\", line 21, in set_up\n    self.driver.close()\n  File \"c:\\users\\z003d7tu\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"c:\\users\\z003d7tu\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\z003d7tu\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568412917634, "stop": 1568412919644}], "start": 1568412876119, "stop": 1568412919644}